<a href="https://colab.research.google.com/github/ickma2311/mycolab/blob/main/statistics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PTP
$$
\text{ptp(a)}=\max(a)-min(a)
$$

In [3]:
import numpy as np

def ptp(arr:np.array,axis:int):
  result=[]
  if axis==0:
    for i in range(arr.shape[1]):
      sub_arr=arr[:,i]
      result.append(np.max(sub_arr)-np.min(sub_arr))
  if axis==1:
    for i in range(arr.shape[0]):
      result.append(np.max(arr[i])-np.min(arr[i]))
  return np.array(result)




In [4]:
import numpy as np
a=np.random.randint(0,100,(10,10))
a=np.array(a,dtype=np.int32,order='C')
ptp(a,axis=1)

array([86, 74, 96, 69, 71, 71, 74, 96, 79, 74], dtype=int32)

In [5]:
np.ptp(a,axis=1)

array([86, 74, 96, 69, 71, 71, 74, 96, 79, 74], dtype=int32)

In [6]:
%%timeit
ptp(a,axis=0)

83.4 µs ± 8.03 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
%%timeit
np.ptp(a,axis=0)

7.29 µs ± 2.01 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [8]:
np.all(ptp(a,axis=0)==np.ptp(a,axis=0))

np.True_

# percentile
$$
x=\{x_1,x_2,...x_N\} \\
r==\frac {q}{100}⋅(N-1)  \\
k=[r],d=r-k \\
\text {percentile}=x[k]+d\times (x_{k+1}-x_k)
$$


In [15]:
def percentile(a:np.array,q:float):
  a=sorted(a)
  r=(q/100)*(len(a)-1)
  if r==len(a)-1:
    return a[-1]
  return a[int(r)]+(r-len(a))*(a[int(r)+1]-a[int(r)])

In [19]:
a=np.random.randint(0,100,1000000)


In [28]:
%%timeit
percentile(a,12)

455 ms ± 22.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [29]:

%%timeit
np.percentile(a,12)

18.1 ms ± 1.7 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
for i in range(0,101,1):
  assert(percentile(a,i)==np.percentile(a,i))

# Pearson Correlation
Given to vectors $x=\{x_1,x_2,...x_n\}$ and $y=\{y_1,y_2,...y_n\}$, the **Pearson Correlation coefficient** is defined as:
$$
p_{x,y}= \frac {\sum_{i=1}^n(x-\bar x)⋅(y-\bar y)} {{\sqrt {\sum_{i=1}^n (x-\bar x)^2 }} \cdot {\sqrt {\sum_{i=1}^n (y- \bar y)^2}}}
$$




In [33]:
def pearson_correlation(x:np.array,y:np.array):
  x_mean=x.mean()
  y_mean=y.mean()
  numbertor=np.sum((x-x_mean)*(y-y_mean))
  numberbot=(np.sqrt(np.sum((x-x_mean)**2))*np.sqrt(np.sum((y-y_mean)**2)))
  return numbertor/numberbot


In [34]:
a=np.random.random(100)
b=np.random.random(100)

In [35]:
pearson_correlation(a,b)

np.float64(-0.13853550345500165)

In [40]:
np.corrcoef(a,b)

array([[ 1.       , -0.1385355],
       [-0.1385355,  1.       ]])