<a href="https://colab.research.google.com/github/ickma2311/mycolab/blob/main/StaticsticLearning/KDTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn.datasets import load_iris

# Load the iris dataset
iris = load_iris()



In [8]:

class KDNode:
  def __init__(self,point,left,right) -> None:
    self.point=point
    self.left=left
    self.right=right


def build_kdtree(data,depth=0):
  if len(data)==0:
    return None
  k=len(data[0])
  axis=depth%k

  sorted_dat=sorted(data,key=lambda x:x[axis])
  median_index=len(sorted_dat)//2
  median_point=sorted_dat[median_index]

  left_points=sorted_dat[:median_index]
  right_points=sorted_dat[median_index+1:]

  return KDNode(median_point,build_kdtree(left_points,depth+1),build_kdtree(right_points,depth+1))







In [9]:
tree=build_kdtree(iris.data)

In [10]:
tree.point

array([5.8, 2.7, 3.9, 1.2])

# Search


In [15]:
import heapq
import numpy as np

def nearest_neighbor(node,target,depth=0,best=None):
  if not node:
    return best

  axis=depth%len(target)

  # current best
  if best is None or np.linalg.norm(node.point-target)<np.linalg.norm(best-target):
    best=node.point

  # check where to go
  if target[axis]<node.point[axis]:
    next_node=node.left
    opposite_node=node.right
  else:
    next_node=node.right
    opposite_node=node.left

  best=nearest_neighbor(next_node,target,depth+1,best)

  # back track
  # check if far side could have a closer point

  if np.abs(target[axis]-node.point[axis])<np.linalg.norm(best-target):
    best=nearest_neighbor(opposite_node,target,depth+1,best)

  return best

In [16]:
nearest_neighbor(tree,iris.data[0])

array([5.1, 3.5, 1.4, 0.2])

In [17]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])