<a href="https://colab.research.google.com/github/ickma2311/mycolab/blob/main/matrix/matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix Add

## Matrics add scalar

$$
\begin{pmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{pmatrix} +s=
\begin{pmatrix}
a+s & b+s & c+s \\
d+s & e+s & f+s \\
g+s & h+s & i+s
\end{pmatrix}
$$

## Matrix add broadcast

$$
\begin{pmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{pmatrix}
+
\begin{pmatrix}
j \\
k \\
l
\end{pmatrix}
=
\begin{pmatrix}
a+j& b+j & c+j \\
d+k & e+k & f+k \\
g+l & h+l & i+l
\end{pmatrix}
$$

## Matrix add matrix

$$
\begin{pmatrix}
a & b & c \\
d & e & f \\
g & h & i
\end{pmatrix}
+
\begin{pmatrix}
j & k & l \\
m & n & o \\
p & q & r
\end{pmatrix}
=
\begin{pmatrix}
a+j & b+k & c+l \\
d+m & e+n & f+o \\
g+p & h+q & i+r
\end{pmatrix}
$$

## Code example

In [16]:

import torch
a=torch.rand(3,2)
print('a is a matrix with shape(3,2)')


# matrix add scalar
print('a+0.1 is a matrix with shape(3,2)')
print(a+0.1)

# matrix add matrix
b=torch.rand(3,2)
print('b is another matrix with shape(3,2)')
print('a+b is a matrix with shape(3,2)')
print(a+b)

# broadcast
c=torch.rand(3,1)
print('c is a vector with shape(3,1)')
print('a+c is a matrix with shape(3,2)')
print(a+c)


a is a matrix with shape(3,2)
a+0.1 is a matrix with shape(3,2)
tensor([[0.6860, 0.3382],
        [0.4839, 0.5033],
        [0.4357, 0.3504]])
b is another matrix with shape(3,2)
a+b is a matrix with shape(3,2)
tensor([[0.8067, 0.4724],
        [0.9208, 0.9055],
        [0.3923, 1.1365]])
c is a vector with shape(3,1)
a+c is a matrix with shape(3,2)
tensor([[1.1250, 0.7772],
        [0.9409, 0.9603],
        [0.8880, 0.8027]])


# Matrix Multiplication

A is a (m,n) matrix and B is a (n,p) matrix.

$$
\mathbf A=
\begin{pmatrix}
a_{11}&a_{12} &...&a_{1n} \\
a_{21}&a_{22}&...&a_{2n} \\
... & ... &... &... \\
a_{m1}&a_{m2}&...&a_{mn}
\end{pmatrix},
\mathbf B=
\begin{pmatrix}
b_{11}&b_{12} &...&b_{1p} \\
b_{21}&b_{22}&...&b_{2p} \\
... & ... &... &... \\
b_{n1}&a_{n2}&...&a_{np}
\end{pmatrix}
$$

$\mathbf A × \mathbf B = \mathbf C=$



$$
\begin{pmatrix}
c_{11}&c_{12}&...&c_{1p}\\
c_{21}&c_{22}&...&c_{2p}\\
... & ... &... &... \\
c_{m1}&c_{m2}&...&c_{mp}
\end{pmatrix}
$$

$$
c_{ij}=a_{i1}×b_{1j}+a_{i2}\times b_{2j}+...+a_{in}\times b{nj}=
\sum_{k=1}^na_{ik}×b_{kj}
$$

Process:
```
for i,row in A: #A is (m.n) so row length is n
  for j,column in B: # B is (m,n) so column length is n)
    r=sum(A1*B1,A2*B2,...An*Bn)
    C[i,j]=r
```


## Code example

In [25]:
a=torch.rand(3,2)
b=torch.rand(2,3)
c=torch.matmul(a,b) #shape(3,3)
print(c)
# Let us verify the c_11
c11=c[0,0]
print("c11 is :",c11)
print(sum(a[0,i]*b[i,0] for i in range(2)))

tensor([[1.2734, 0.6060, 0.3447],
        [0.8384, 0.4447, 0.2421],
        [0.4645, 0.2310, 0.1290]])
c11 is : tensor(1.2734)
tensor(1.2734)
